version: '3'
services:
  app:
    container_name: docker-node-postgres
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
